version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: "rabbit_cookie"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
      - "1883:1883"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    command: >
          bash -c "rabbitmq-plugins enable --offline rabbitmq_mqtt && rabbitmq-server"
    restart: always
networks:
  default:
    driver: bridge
volumes:
  rabbitmq_data: {}
